version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    volumes:
      - ./app:/src/app/app
      - app-data:/src/data
volumes:
  app-data:
